title: Default Page

tabs:
  content:
    columns:
      main:
        width: 3/4
        sections:
          fields:
            type: fields
            fields:
              text:
                extends: fields/layout
      side:
        width: 1/4
        sections:
          subpages:
            type: pages
  media:
    sections:
      files:
        type: files
  
  security:
    icon: lock
    columns:
      - width: 1/3
        fields:
          pageProtect: fields/locked-pages


  settings:
    icon: cog
    extends: layouts/page-settings