title: Default Page

columns:
  main:
    width: 1
    sections:
      fields:
        type: fields
        fields:
          text:
            type: blocks
            size: huge
            fieldsets:
              text:
                label: Text
                type: group
                fieldsets:
                  - heading
                  - text
                  - list
              media:
                label: Media
                type: group
                fieldsets:
                  image:
                    extends: blocks/image
                    fields:
                      full:
                        label: Full Width
                        type: toggle
                        text:
                          - "no"
                          - "yes"
                  video:
                    extends: blocks/video
              code:
                label: Code
                type: group
                open: false
                fieldsets:
                  - code
                  - markdown

